version: 2.1
jobs:
  test:
    docker:
      - image: &img cimg/rust:1.56
    steps:
      - checkout
      - run:
          name: Tests
          command: |
            cargo test --all-targets
            RUSTFLAGS="--cfg loom" cargo test --all-targets
  checks:
    docker:
      - image: *img
    steps:
      - checkout
      - run: cargo clippy
      - run:
          name: cargo doc
          command: cargo doc --no-deps

workflows:
  full:
    jobs:
      - test
      - checks