version: 2.1
orbs:
  rust: circleci/rust@1.6.0
  codecov: codecov/codecov@3.2.4
jobs:
  build:
    docker: 
      - image: &img cimg/rust:1.64
    steps:
      - checkout
      - rust/build
  test:
    docker:
      - image: *img
    steps:
      - checkout
      - run:
          name: Tests
          command: cargo test --all-targets
  nightly_test:
    docker:
      - image: *img
    steps:
      - checkout
      - rust/install:
          version: nightly
      - run:
          name: Nightly Tests
          command: cargo +nightly test --all-targets --all-features
  loom:
    docker:
      - image: *img
    resource_class: large
    steps:
      - checkout
      - run:
          name: Loom
          command: RUSTFLAGS="--cfg loom" cargo test --all-targets --release
  checks:
    docker:
      - image: *img
    steps:
      - checkout
      - rust/install:
          version: nightly
      - run: cargo clippy
      - run:
          name: cargo doc
          command: cargo +nightly doc --no-deps
      - run:
          name: no_std
          command: cargo test --no-default-features
    parallelism: 3
  coverage:
    docker:
      - image: *img
    steps:
      - checkout
      - rust/install:
        version: nightly
      - run: rustup component add llvm-tools-preview
      - run: cargo install cargo-llvm-cov
      - run: cargo llvm-cov --lcov --output-path lcov.info
      - run: cargo +nightly llvm-cov --lcov --all-features --output-path lcovnightly.info
      - codecov/upload: 
          file: lcov.info
          flags: stable
      - codecov/upload: 
          file: lcovnightly.info
          flags: nightly
workflows:
  full:
    jobs:
      - build
      - test
      - loom
      - checks
      - coverage:
          context: CODECOV_TOKEN