version: 2.1
orbs:
  rust: circleci/rust@1.6.0
jobs:
  test:
    docker:
      - image: &img cimg/rust:1.64
    steps:
      - checkout
      - run:
          name: Tests
          command: cargo test --all-targets
  nightly_test:
    docker:
      - image: *img
    steps:
      - checkout
      - rust/install:
          version: nightly
      - run:
          name: Nightly Tests
          command: cargo +nightly test --all-targets --all-features
  loom:
    docker:
      - image: *img
    resource_class: large
    steps:
      - checkout
      - run:
          name: Loom
          command: RUSTFLAGS="--cfg loom" cargo test --all-targets --release
  checks:
    docker:
      - image: *img
    steps:
      - checkout
      - run: cargo clippy
      - run:
          name: cargo doc
          command: cargo doc --no-deps
      - run:
          name: no_std
          command: cargo test --no-default-features
    parallelism: 3
workflows:
  full:
    jobs:
      - test
      - loom
      - checks