version: 2.1
jobs:
  test:
    docker:
      - image: &img cimg/rust:1.56
    steps:
      - run:
          name: Tests
          command: |
            cargo test --all-features --all-targets
            RUSTFLAGS="--cfg loom" cargo test --all-features --all-targets
  checks:
    docker:
      - image: *img
    steps:
      - run: cargo clippy
      - run: cargo fmt --check
      - run:
          name: cargo doc
          command: cargo doc --no-deps --all-features

workflows:
  full:
    jobs:
      - test
      - checks