version: 2.1
jobs:
  test:
    docker:
      - image: &img cimg/rust:1.64
    steps:
      - checkout
      - run:
          name: Tests
          command: |
            cargo test --all-targets
  loom:
    docker:
      - image: *img
    resource_class: large
    steps:
      - checkout
      - run:
          name: Loom
          command: RUSTFLAGS="--cfg loom" cargo test --all-targets --release
  checks:
    docker:
      - image: *img
    steps:
      - checkout
      - run: cargo clippy
      - run:
          name: cargo doc
          command: cargo doc --no-deps

workflows:
  full:
    jobs:
      - test
      - loom
      - checks